Var pix centralize
Orama-Interactive/Pixelorama pull request #441
Opened 2021-01-23 19:18 UTC by Variable-ind

Th change in these files allow me to create the Centralize function

2021-01-24 21:36 UTC, OverloadedOrama requested changes
I tested it and it works well. I left some comments in your code with some of my thoughts and minor changes I would like to see, so please read those. But overall this is very nice and it should be almost ready to get merged. Good job!

2021-01-24 21:36 UTC, OverloadedOrama commented on src/Autoload/DrawingAlgos.gd
> +func general_do_centralize(width : int, height : int) -> void:
These paremeters are not required

2021-01-24 21:36 UTC, OverloadedOrama commented on src/Autoload/DrawingAlgos.gd
> +	var img_position = used_rect.position   # Now we have the boundaries
Some of these comments are a bit redundant; a lot of the code is already quite readable and understandable. I would suggest only keeping some comments that explain what the function does and how it works. Also note that we should try to stick to the [GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#comment-spacing) as much as possible, so comments should start with a single # and followed by a single space.

2021-01-24 21:36 UTC, OverloadedOrama commented on src/Autoload/Global.gd
> +	#minor change by Variable (i added action_name == "Centralize" here)
I would advice not putting your name in every single change you contribute, as it may confuse future code readers. Contributors are already being credited in the About dialog, the CHANGELOG.md file, and git keeps track of every single change being made to every file, and remembers the authors of the changes. If you want to keep your name in the code, I would prefer if you only put it in completely new methods that you added, like the centralize method in DrawingAlgos.gd

2021-01-24 21:36 UTC, OverloadedOrama commented on src/UI/TopMenuContainer.gd
> +########Minor addition by Variable
Same comments about your username and comment style applies in this file as well.

2021-01-25 08:02 UTC, Variable-ind commented on src/Autoload/Global.gd
> +	#minor change by Variable (i added action_name == "Centralize" here)
Oh sorry i just added the comments to quickly locate my changes

2021-01-25 09:10 UTC, Variable-ind commented on src/Autoload/DrawingAlgos.gd
> +func general_do_centralize(width : int, height : int) -> void:
Thanks for letting me know. i have now removed them.

2021-01-25 12:54 UTC, kleonc reviewed
I also took a look. Works fine but here are some of my suggestions:

2021-01-25 12:54 UTC, kleonc commented on src/Autoload/DrawingAlgos.gd
> +
There should be 2 empty lines between the methods.

2021-01-25 12:54 UTC, kleonc commented on src/Autoload/DrawingAlgos.gd
There should be 2 empty lines between the methods.

2021-01-25 12:54 UTC, kleonc commented on src/UI/TopMenuContainer.gd
> +
And there's no need for 2 empty lines, remove one.

2021-01-25 12:54 UTC, kleonc commented on src/Autoload/DrawingAlgos.gd
> +		sprite.blend_rect(c.image, Rect2(Vector2.ZERO, Global.current_project.size), Vector2(offset_x, offset_y))
There's no need to blend the whole cel's image, there's `used_rect` already calculated.
```suggestion
	var offset : Vector2 = (0.5 * (Global.current_project.size - used_rect.size)).floor()
	general_do_centralize()
	for c in Global.current_project.frames[Global.current_project.current_frame].cels:
		var sprite := Image.new()
		sprite.create(Global.current_project.size.x, Global.current_project.size.y, false, Image.FORMAT_RGBA8)
		sprite.blend_rect(c.image, used_rect, offset)
```

2021-01-25 13:57 UTC, Variable-ind commented on src/Autoload/DrawingAlgos.gd
> +		return
Done! thanks

2021-01-25 14:44 UTC, kleonc commented on src/Autoload/DrawingAlgos.gd
It's outdated and not really needed (there's another comment below about finding frame's used rect).
```suggestion	
```

2021-01-25 14:49 UTC, kleonc approved these changes

2021-01-25 14:49 UTC, Variable-ind commented on src/Autoload/DrawingAlgos.gd
Done

2021-01-26 14:03 UTC, OverloadedOrama approved these changes
Thank you!

2021-01-26 14:03 UTC, merged