Var transparent mode
Orama-Interactive/Pixelorama pull request #444
Opened 2021-01-29 10:21 UTC by Variable-ind

I modified my earlier version a little bit so that it would reset to zero in full screen mode hence removing the blackness issue

2021-01-29 11:28 UTC, kleonc commented
For sure you're not blending colors correctly:
<details>
<summary>Opaque image (100% transparent mode)</summary>

![yZdInjYGI6](https://user-images.githubusercontent.com/9283098/106268178-02802380-622b-11eb-891d-f18b29ec991c.png)
</details>

<details>
<summary>Not opaque image (100% transparent mode) </summary>

#### It's too dark, blending with the white background shouldn't make it darker.
![NZNlnAZWzn](https://user-images.githubusercontent.com/9283098/106268484-7c181180-622b-11eb-9fb1-41baf0de47a2.png)
</details>

---
Setting blending mode to premultiplied alpha for the main ViewportContainer seems to fix it:
<details>
<summary>Not opaque image (100% transparent mode).</summary>

![EqRnzyV5uG](https://user-images.githubusercontent.com/9283098/106268219-13309980-622b-11eb-9ef7-bc8b88cfd530.png)
</details>

2021-01-29 12:02 UTC, Variable-ind commented
it is mot a bug. If you look at the code, the transparency does not affect the image(even a little bit), it only effects the checker shader and the background.

2021-01-29 12:13 UTC, Variable-ind commented
however it does seem to get the job done so i am going to add it

2021-01-29 12:21 UTC, kleonc commented
> it is not a bug. If you look at the code, the transparency does not affect the image(even a little bit), it only effects the TransparentChecker.shader and the background.

Image can be transparent and thus its colors are already multiplied by alpha of the layers etc. So if you're changing Viewport's background to be transparent you need to take into account that the alpha was already applied to the image (RGB values of the image are already multiplied by the alpha). Otherwise you'll end up with the darker colors when `backgroundAlpha != 1.0` because RGB values of the image would be again multiplied by some factor < 1.0 (which you can see happening on the image in my previous comment).

2021-01-29 12:23 UTC, Variable-ind commented
yes i found it just now and am enabling material.blend_mode = CanvasItemMaterial.BLEND_MODE_PREMULT_ALPHA thanks for letting me know

2021-02-01 16:09 UTC, OverloadedOrama requested changes
It seems to be working well, good job! I left some comments too, and I would also like to propose to change "Transparency Mode" to "Window Transparency", in order to make what the option does more obvious to the user. As for the option's UI, I'm still unsure if this is a good place for it, but I suppose we could leave it as it is for now, and we could change it in the future if we think of something better.

2021-02-01 16:09 UTC, OverloadedOrama commented on src/Main.gd
> +	var Alternate_transparent_Background = ColorRect.new()
Rather minor, but make sure variable names are in snake_case, according to [GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#functions-and-variables). So the variable name should be alternate_transparent_background

2021-02-01 16:09 UTC, OverloadedOrama commented on src/Main.gd
> +	Alternate_transparent_Background.name = "Alternate transparent Background"
Same as the above comment, node names should be in PascalCase, according to the [GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#classes-and-nodes). The node's name should be AlternateTransparentBackground.

2021-02-01 17:59 UTC, Variable-ind commented on src/Main.gd
> +	var Alternate_transparent_Background = ColorRect.new()
Done

2021-02-01 17:59 UTC, Variable-ind commented on src/Main.gd
> +	Alternate_transparent_Background.name = "Alternate transparent Background"
Done

2021-02-02 15:29 UTC, OverloadedOrama approved these changes
All right, awesome, thank you!

2021-02-02 15:29 UTC, merged