full support for auto tallscreen/widescreen panel layout
Orama-Interactive/Pixelorama pull request #458
Opened 2021-02-22 06:54 UTC by ballerburg9005

If the window aspect ratio is lowered below 3:4, then the panel layout will switch to "tallscreen", which entails that the right toolbar will be moved to the bottom instead. Of course the reverse is also true. The user can manually override the panel layout behavior in View -> Panel Layout.

Tested with Godot 3.2.1 on Linux and HTML5 with Chrome. Should be pretty error-proof though.

![widescreen_mode](https://user-images.githubusercontent.com/50874674/108672076-bfd80100-74e1-11eb-90b6-cd9baf6693d2.jpg)
![tallscreen_mode](https://user-images.githubusercontent.com/50874674/108672086-c4041e80-74e1-11eb-9dbc-69fc8f420f47.jpg)

2021-02-22 10:46 UTC, ballerburg9005 commented
The canvas preview now hides, when there is not enough room due to display scaling.

![tallscreen_mode2](https://user-images.githubusercontent.com/50874674/108697680-75677c00-7503-11eb-8e2c-6fbf22e8b4ee.jpg)

2021-02-22 10:49 UTC, ballerburg9005 commented
The canvas preview now hides, when there is not enough room due to display scaling.

![tallscreen_mode2](https://user-images.githubusercontent.com/50874674/108698056-f9216880-7503-11eb-9cbc-a43eab556724.jpg)

2021-02-22 16:00 UTC, ballerburg9005 commented
![tallscreen_vs_widescreen](https://user-images.githubusercontent.com/50874674/108734192-7f9f6f80-752f-11eb-8362-2db70d5c44f5.jpg)

2021-02-23 14:09 UTC, Erevoid commented
Pixelorama supporting vertical screens is a very important addition and thanks for making it. I made a concept of a more organised version of what you made, with a bit more drawing space and a slight visual UI placement improvement. What do you think?
![suggestion](https://user-images.githubusercontent.com/58960464/108855246-78409a80-75f1-11eb-9e48-a201dd265297.png)

2021-02-23 19:44 UTC, ballerburg9005 commented
You are welcome! I was afraid that you maybe wouldn't appreciate tallscreen support.

I have made the changes, except for the color picker, which I overlooked.

I am a little bit hesitant to move too many elements around, as later changes in the UI would also require the script to change.

Moving the color picker is a bit ... hmm, I really don't know!

Check out how it is so far:

![tallscreen](https://user-images.githubusercontent.com/50874674/108896948-d3848400-7615-11eb-9624-59aef06bf7cb.jpg)

I later noticed that it is most important to minimize the mouse distance to the tools. With the tools tool panel at the bottom, it is a tad bit longer, but you will make the same downward movement every time, which I believe is more intuitive.

If you still really want the color picker above the CanvasPreview, I can do it as well.

2021-02-24 12:10 UTC, Erevoid commented
I'm a fan of the layers being moved on the bottom. It looks good so far! The tools may need a second column in the future and that would greatly decrease the canvas area visible in vertical screens. While the colour picker looks good when the preview is removed, when the preview is there it has empty space under it and it seems unbalanced (visually). I would suggest having it at its current position without the preview and when the preview is enabled have it over it? As for the tools being moved down there, it may even require less mouse movements if you need to choose a tool and change its tool options so I think it's ideal now!

2021-02-25 19:22 UTC, ballerburg9005 commented
Final result. Please merge.

![ts2](https://user-images.githubusercontent.com/50874674/109205640-26da0c00-77a7-11eb-9713-d297a5f4f6ea.jpg)

2021-03-01 20:53 UTC, OverloadedOrama requested changes

2021-03-01 20:53 UTC, OverloadedOrama commented on src/Main.gd
> +
Minor issue, but for readability purposes, make sure that the code follows the GDScript style guide, namely the [whitespace guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#whitespace) and [variable naming conventions](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#functions-and-variables). Variable names should be in snake_case.

2021-03-01 21:48 UTC, ballerburg9005 commented
It's your program, but I would suggest you keep it as it was. I specifically made exceptions to the rule, because it turned out to be more readable and the variable names 1:1 matched the actual Node names, which is cleaner and more useful.

2021-03-01 22:14 UTC, ballerburg9005 commented on src/Main.gd
> +
It's your program, but I would suggest you keep it as it was. I specifically made exceptions to the rule, because it turned out to be more readable and the variable names 1:1 matched the actual Node names, which is cleaner and more useful.

2021-03-03 14:58 UTC, OverloadedOrama commented on src/Main.gd
> +
I understand the reasoning, but since the rest of the code follows (or at least, tries to follow) the GDScript style guide, for the sake of code consistency, I think it would be better if there are no exceptions. I plan to go through all of the rest of the code at some point and spot inconsistencies that may have occurred and fix them.

Alternatively, we could rewrite all of the other node variable names to match the node names (or rename the nodes to match the variables), but I'm not sure if this is worth the effort.

2021-03-03 15:25 UTC, OverloadedOrama reviewed
Tested it more and it seems to be working well. Left a couple more comments and after they get resolved, it should be ready to get merged!

2021-03-03 15:25 UTC, OverloadedOrama commented on src/Classes/Project.gd
> +		Global.panel_layout_submenu.set_item_checked(j, j == panel_layout)
Is the panel layout meant to be a per-project setting? Because if I, for example, select Tallscreen and then switch tabs, the submenu item that is checked returns to Auto, but the UI does not change.

Per-project setting means that the UI would change depending on the project, each project would have its own panel layout. If this is something we want, then this code also needs to call `change_ui_layout()` from Main.gd. If this is something we don't want, then these 3 new lines of code should be removed completely. Personally, I don't think it should be a per-project setting as it's a UI change that may confuse the users.

2021-03-03 15:25 UTC, OverloadedOrama commented on src/UI/TopMenuContainer.gd
> +	for i in Global.TileMode.values():
I think this line should be `for i in Global.PanelLayout.values():`.

2021-03-04 17:21 UTC, ballerburg9005 reviewed
Check out new commit.

2021-03-04 17:21 UTC, ballerburg9005 commented on src/Classes/Project.gd
> +		Global.panel_layout_submenu.set_item_checked(j, j == panel_layout)
It will now save and restore the layout if you close and reopen the window. 

On that matter: shouldn't most other global view settings also save and restore? If the users sets a different window transparency or hides the animation timeline for example. Maybe not tile mode though and especially not mirror view.

Honestly, when I tied panel_layout to current_project I wasn't sure whether or not saving the view settings were broken. So I didn't think it through any further.

2021-03-04 17:21 UTC, ballerburg9005 commented on src/UI/TopMenuContainer.gd
> +	for i in Global.TileMode.values():
Check out new commit.

2021-03-04 17:21 UTC, ballerburg9005 commented on src/UI/TopMenuContainer.gd
> +	for i in Global.TileMode.values():
fixed

2021-03-06 13:59 UTC, OverloadedOrama approved these changes
Looks good to me. Thank you!

2021-03-06 13:59 UTC, merged