Made Image brush obey dynamics as well
Orama-Interactive/Pixelorama pull request #828
Opened 2023-02-21 13:17 UTC by Variable-ind

https://user-images.githubusercontent.com/77773850/220355068-71b73143-625b-4868-94a8-d167bf1d546c.mp4

2023-02-21 13:42 UTC, Variable-ind commented
i have also added a changed signal in the global tool options that will reset the dynamics whenever a change is made

https://user-images.githubusercontent.com/77773850/220361700-415c20ca-51f3-4cee-ac2a-0a1b53249ff3.mp4

2023-02-21 14:49 UTC, Variable-ind commented
Added progress bar to Thresholds
 
https://user-images.githubusercontent.com/77773850/220377377-48a4b8b0-82c1-4424-9ea8-c718a6b1d2c2.mp4

2023-02-28 13:12 UTC, OverloadedOrama requested changes
Besides the comments I've left, everything looks pretty good!

2023-02-28 13:30 UTC, Variable-ind commented on src/UI/GlobalToolOptions/GlobalToolOptions.gd
> +			if pressure_rect.has_point(get_global_mouse_position()):
Done

2023-02-28 13:30 UTC, Variable-ind commented on src/UI/GlobalToolOptions/GlobalToolOptions.gd
> +signal changed
Done

2023-02-28 15:07 UTC, OverloadedOrama approved these changes
Looks good, thank you!

2023-02-28 15:07 UTC, merged